# Site settings
# vim: nospell
port: 4000
output: _dist
title: Mini Jekyll
description: The smallest Jekyll website !
email: michelc@gc-bank.org
baseurl: ""
url: "//jekyll.tk" # the base hostname & protocol for your site
url: "https://michel47.github.io"
netname: modest-pare-29d464
url: "https://modest-pare-29d464.netlify.net"
googledocid: 1VfERUZ8oTEGlCT3Xn37yK1TOsYxFZuJryNNR7bhJdUM
framaid: mini_jekyll

exclude:
 - publish.sh
 - .org
 - _site
 - Gemfile
 - Gemfile.lock
 - travis.sh
