# Site settings
# vim: nospell
port: 4000
output: _dist
title: Self.Health.Quant
description: A blockchain for your self health Quantification
domain: shqb.ml
date: 2019-09-24 18:04:23 CEST
creation: 2019-09-15 12:39:08 CEST
update: 2019-09-15 12:39:08 CEST
name: SHQB
author: "Michel G. Combes"
email: michelc@gc-bank.org
baseurl: ""
url: "//jekyll.tk" # the base hostname & protocol for your site
url: "https://michel47.github.io/shqb.ml/"
netname: modest-pare-29d464
url: "https://modest-pare-29d464.netlify.net"
search: "https://duckduckgo.com/?q"
googledocid: 1VfERUZ8oTEGlCT3Xn37yK1TOsYxFZuJryNNR7bhJdUM
framaid: shqb
gtag: UA-146588632-1

exclude:
 - publish.sh
 - .org
 - _site
 - Gemfile
 - Gemfile.lock
 - travis.sh
